// Re-export all shared domain types from the ui package for convenience
export type {
  PaginatedResponse,
  ApiResponse,
  ApiError,
  ProductStatus,
  ProductType,
  ProductCategory,
  ProductBrand,
  ProductImage,
  ProductVariant,
  Product,
  CartItem,
  Cart,
  UserRole,
  Address,
  User,
  AuthTokens,
  AuthResponse,
  OrderStatus,
  PaymentStatus,
  PaymentMethod,
  OrderItem,
  Order,
  Review,
  ProductFilters,
  DashboardStats,
  RevenueDataPoint,
  TopProduct,
} from '@mcduffcare/ui/types';
